### ISSUE TITLE
Template .gitignore not found

### ISSUE THREAD

**Issue by martenlienen** [AdrieanKhisbe/cask-package-toolset.el#1]
Hi,
I have just created a new project with a basic `Cask` file, installed this package through it and then ran

``` sh
$ cask exec package-toolset install
Template .gitignore not found
```

It creates some files, but the `.gitignore` file is missing. For now I will just add it manually, but I though you should know.

**Comment by AdrieanKhisbe** [comment]
Hey @cqql,
that's a know bug that wasn't in my head right now when I made the announcement. :)

It's coming from the fact that when packaging, melpa exclude the `.gitgnore` because some old rule: cf
https://github.com/milkypostman/melpa/issues/2808

Hence cpt don't find it in it's template directory.
Thanks for the reminder, I'm gonna poke melpa :)

**Comment by AdrieanKhisbe** [comment]
Melpa change has been made, I locally tested it, it worked.
So we just have to wait new build cycle. (I push modification so that cpt is rebuilt).
If it works I'll realease as 0.6.5 tag to have the stable rebuild.

It's coming! :)

**Comment by martenlienen** [comment]
Thanks :)

I will test it again later.

**Comment by AdrieanKhisbe** [comment]
Just tested it, it works. Releasing 0.6.5 then :)

**Comment by martenlienen** [comment]
Yes, it does. Thanks for the help :)

**Comment by AdrieanKhisbe** [comment]
you're welcome! :)
thanks for reminding me of this bug
